### ISSUE TITLE
closing auto 

### ISSUE THREAD

**Issue by cansavrun** [sawankumarbundelkhandi/edge_detection#74]
How can we add the choice to take photos automatically or manually in ios?

**Comment by sawankumarbundelkhandi** [comment]
I have fixed this in the latest commit.

Meanwhile, you can use it directly from Github like this

In pubspec, specify dependency like below

```
dependencies:
edge_detection:
 git:
  url: git://github.com/sawankumarbundelkhandi/edge_detection.git
```
